# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hub < Formula
  desc "Hub CLI is stack composition and lifecycle tool."
  homepage "https://superhub.io/"
  version "1.0.8"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/agilestacks/hub/releases/download/v1.0.8/hub_Darwin_x86_64.tar.gz"
      sha256 "c758a9a9bd73bb2cdda2522771ec100922f46293e4454380f2a73e9caa600514"

      def install
        bin.install "hub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/agilestacks/hub/releases/download/v1.0.8/hub_Darwin_arm64.tar.gz"
      sha256 "3bf6c28957a02e59a4c1dd46347afe19147463e2fa61b27d0e9d9dfe8ed074e0"

      def install
        bin.install "hub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/agilestacks/hub/releases/download/v1.0.8/hub_Linux_arm64.tar.gz"
      sha256 "57a89aa3715378e59214f569b5a2adae4cf754a74078f66b6c4218e9e6e2dae4"

      def install
        bin.install "hub"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/agilestacks/hub/releases/download/v1.0.8/hub_Linux_x86_64.tar.gz"
      sha256 "b00fc9f7a40bd29c0e9bfe54eab85adcd0bc4948cbfe4246e6906b9b30abf409"

      def install
        bin.install "hub"
      end
    end
  end

  head "https://github.com/asibot/hub"

  depends_on "jq"
  depends_on "yq"
  depends_on "npm" => :optional

  def post_install
    hub_home = Pathname.new "#{Dir.home}/.hub"
    unless hub_home.exist?
        system "#{Formula["hub"].opt_bin}/hub", "extensions", "install"
    end
  end

  def caveats; <<~EOS
    hub version
    hub help
    hub elaborate hub.yaml params.yaml -o hub.yaml.elaborate
    hub deploy hub.yaml.elaborate -e NAME=stage
  EOS
  end

  test do
    output = shell_output("#{bin}/hub version").chomp
    assert output.start_with?("Hub CLI git ")
    system "false"
  end
end
